#!/bin/bash

# Script to generate Nginx configuration for Fridgr application
# Usage: ./generate-nginx-conf.sh <domain>
# Example: ./generate-nginx-conf.sh pantrybot.app

set -e

# Check if domain argument is provided
if [ $# -eq 0 ]; then
    echo "Error: Domain name is required"
    echo "Usage: $0 <domain>"
    echo "Example: $0 pantrybot.app"
    exit 1
fi

DOMAIN=$1
CONFIG_FILE="${DOMAIN}.conf"

echo "Generating Nginx configuration for domain: ${DOMAIN}"

# Create the Nginx configuration file
cat > "${CONFIG_FILE}" << 'EOF'
# Nginx configuration for Fridgr application
# Auto-generated by generate-nginx-conf.sh

# Upstream configuration for frontend
upstream fridgr_frontend {
    server localhost:3010;
}

# Upstream configuration for mock backend API
upstream fridgr_api {
    server localhost:8088;
}

# Main domain - Frontend application
server {
    listen 80;
    listen [::]:80;
    server_name DOMAIN_PLACEHOLDER;

    # Redirect HTTP to HTTPS (will be handled by certbot later)
    # location / {
    #     return 301 https://$server_name$request_uri;
    # }

    # Frontend proxy configuration
    location / {
        proxy_pass http://fridgr_frontend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Timeout settings
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Next.js specific paths
    location /_next {
        proxy_pass http://fridgr_frontend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Static files
    location /static {
        proxy_pass http://fridgr_frontend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Cache static assets
        proxy_cache_valid 200 1d;
        proxy_cache_bypass $http_pragma;
        proxy_cache_revalidate on;
    }
}

# API subdomain - Backend/Mock Backend API
server {
    listen 80;
    listen [::]:80;
    server_name api.DOMAIN_PLACEHOLDER;

    # Redirect HTTP to HTTPS (will be handled by certbot later)
    # location / {
    #     return 301 https://$server_name$request_uri;
    # }

    # API proxy configuration
    location / {
        proxy_pass http://fridgr_api;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # CORS headers (if needed)
        add_header 'Access-Control-Allow-Origin' 'https://DOMAIN_PLACEHOLDER' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        
        # Handle OPTIONS requests
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'https://DOMAIN_PLACEHOLDER' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }
        
        # Timeout settings
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # WebSocket support for real-time features
    location /ws {
        proxy_pass http://fridgr_api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # WebSocket specific timeouts
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
    }

    # Health check endpoint
    location /health {
        proxy_pass http://fridgr_api/health;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        access_log off;
    }
}
EOF

# Replace domain placeholder with actual domain
sed -i "s/DOMAIN_PLACEHOLDER/${DOMAIN}/g" "${CONFIG_FILE}"

echo "✓ Nginx configuration generated successfully: ${CONFIG_FILE}"
echo ""
echo "Next steps:"
echo "1. Review the generated configuration: cat ${CONFIG_FILE}"
echo "2. Copy to Nginx sites-available: sudo cp ${CONFIG_FILE} /etc/nginx/sites-available/"
echo "3. Enable the site: sudo ln -s /etc/nginx/sites-available/${CONFIG_FILE} /etc/nginx/sites-enabled/"
echo "4. Test configuration: sudo nginx -t"
echo "5. Reload Nginx: sudo systemctl reload nginx"